name: Ballerina CI

on:
  push:
  	paths:
      - "Backend/**"
	branches: ["Master"]

  pull_request:
	paths:
	  - "Backend/**"
	branches: ["Master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Install Ballerina
        run: |
          curl -L https://dist.ballerina.io/downloads/2201.10.1/ballerina-2201.10.1-swan-lake.zip -o ballerina.zip
          unzip ballerina.zip -d $HOME
          echo "$HOME/ballerina-2201.10.1-swan-lake/bin" >> $GITHUB_PATH

      - name: Add Ballerina to PATH
        run: echo "PATH=$HOME/ballerina-2201.10.1-swan-lake/bin:$PATH" >> $GITHUB_ENV

      - name: Build the Ballerina project
        run: |
          cd Backend
          bal build
